import { StyleSheet } from 'react-native';
export const Styles = StyleSheet.create({
  card: {
    padding: 4,
    borderRadius: 4,
  },
  flexRow: {
    flexDirection: 'row',
  },
  flexColumn: {
    flexDirection: 'column',
  },
  flexRowReverse: {
    flexDirection: 'row-reverse',
  },
  flexColumnReverse: {
    flexDirection: 'column-reverse',
  },
  alignItemsCenter: {
    alignItems: 'center',
  },
  alignItemsBaseline: {
    alignItems: 'baseline',
  },
  alignItemsFlexEnd: {
    alignItems: 'flex-end',
  },
  alignItemsFlexStart: {
    alignItems: 'flex-start',
  },
  alignItemsStretch: {
    alignItems: 'stretch',
  },
  justifyContentCenter: {
    justifyContent: 'center',
  },
  justifyContentFlexEnd: {
    justifyContent: 'flex-end',
  },
  justifyContentFlexStart: {
    justifyContent: 'flex-start',
  },
  justifyContentSpaceAround: {
    justifyContent: 'space-around',
  },
  justifyContentSpaceBetween: {
    justifyContent: 'space-between',
  },
  justifyContentSpaceEvenly: {
    justifyContent: 'space-evenly',
  },
  alignSelfAuto: {
    alignSelf: 'auto',
  },
  alignSelfBaseLine: {
    alignSelf: 'baseline',
  },
  alignSelfCenter: {
    alignSelf: 'center',
  },
  alignSelfFlexEnd: {
    alignSelf: 'flex-end',
  },
  alignSelfFlexStart: {
    alignSelf: 'flex-start',
  },
  alignSelfstretch: {
    alignSelf: 'stretch',
  },
  flex: {
    flex: 1,
  },
  flexNull: {
    flex: 0,
  },
  flexGrow: {
    flexGrow: 1,
  },
  flexGrowNull: {
    flexGrow: 0,
  },
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  p0: { padding: 0 },
  pt0: { paddingTop: 0 },
  pr0: { paddingRight: 0 },
  pb0: { paddingBottom: 0 },
  pl0: { paddingLeft: 0 },
  m0: { margin: 0 },
  mt0: { marginTop: 0 },
  mr0: { marginRight: 0 },
  mb0: { marginBottom: 0 },
  ml0: { marginLeft: 0 },
  br0: { borderRadius: 0 },
  bw0: { borderWidth: 0 },
  bwt0: { borderTopWidth: 0 },
  bwr0: { borderRightWidth: 0 },
  bwb0: { borderBottomWidth: 0 },
  bwl0: { borderLeftWidth: 0 },
  p1: { padding: 4 },
  pt1: { paddingTop: 4 },
  pr1: { paddingRight: 4 },
  pb1: { paddingBottom: 4 },
  pl1: { paddingLeft: 4 },
  m1: { margin: 4 },
  mt1: { marginTop: 4 },
  mr1: { marginRight: 4 },
  mb1: { marginBottom: 4 },
  ml1: { marginLeft: 4 },
  br1: { borderRadius: 4 },
  bw1: { borderWidth: 1 },
  bwt1: { borderTopWidth: 1 },
  bwr1: { borderRightWidth: 1 },
  bwb1: { borderBottomWidth: 1 },
  bwl1: { borderLeftWidth: 1 },
  p2: { padding: 8 },
  pt2: { paddingTop: 8 },
  pr2: { paddingRight: 8 },
  pb2: { paddingBottom: 8 },
  pl2: { paddingLeft: 8 },
  m2: { margin: 8 },
  mt2: { marginTop: 8 },
  mr2: { marginRight: 8 },
  mb2: { marginBottom: 8 },
  ml2: { marginLeft: 8 },
  br2: { borderRadius: 8 },
  bw2: { borderWidth: 2 },
  bwt2: { borderTopWidth: 2 },
  bwr2: { borderRightWidth: 2 },
  bwb2: { borderBottomWidth: 2 },
  bwl2: { borderLeftWidth: 2 },
  p3: { padding: 12 },
  pt3: { paddingTop: 12 },
  pr3: { paddingRight: 12 },
  pb3: { paddingBottom: 12 },
  pl3: { paddingLeft: 12 },
  m3: { margin: 12 },
  mt3: { marginTop: 12 },
  mr3: { marginRight: 12 },
  mb3: { marginBottom: 12 },
  ml3: { marginLeft: 12 },
  br3: { borderRadius: 12 },
  bw3: { borderWidth: 3 },
  bwt3: { borderTopWidth: 3 },
  bwr3: { borderRightWidth: 3 },
  bwb3: { borderBottomWidth: 3 },
  bwl3: { borderLeftWidth: 3 },
  p4: { padding: 16 },
  pt4: { paddingTop: 16 },
  pr4: { paddingRight: 16 },
  pb4: { paddingBottom: 16 },
  pl4: { paddingLeft: 16 },
  m4: { margin: 16 },
  mt4: { marginTop: 16 },
  mr4: { marginRight: 16 },
  mb4: { marginBottom: 16 },
  ml4: { marginLeft: 16 },
  br4: { borderRadius: 16 },
  bw4: { borderWidth: 4 },
  bwt4: { borderTopWidth: 4 },
  bwr4: { borderRightWidth: 4 },
  bwb4: { borderBottomWidth: 4 },
  bwl4: { borderLeftWidth: 4 },
  p5: { padding: 20 },
  pt5: { paddingTop: 20 },
  pr5: { paddingRight: 20 },
  pb5: { paddingBottom: 20 },
  pl5: { paddingLeft: 20 },
  m5: { margin: 20 },
  mt5: { marginTop: 20 },
  mr5: { marginRight: 20 },
  mb5: { marginBottom: 20 },
  ml5: { marginLeft: 20 },
  br5: { borderRadius: 20 },
  bw5: { borderWidth: 5 },
  bwt5: { borderTopWidth: 5 },
  bwr5: { borderRightWidth: 5 },
  bwb5: { borderBottomWidth: 5 },
  bwl5: { borderLeftWidth: 5 },
  p6: { padding: 24 },
  pt6: { paddingTop: 24 },
  pr6: { paddingRight: 24 },
  pb6: { paddingBottom: 24 },
  pl6: { paddingLeft: 24 },
  m6: { margin: 24 },
  mt6: { marginTop: 24 },
  mr6: { marginRight: 24 },
  mb6: { marginBottom: 24 },
  ml6: { marginLeft: 24 },
  br6: { borderRadius: 24 },
  bw6: { borderWidth: 6 },
  bwt6: { borderTopWidth: 6 },
  bwr6: { borderRightWidth: 6 },
  bwb6: { borderBottomWidth: 6 },
  bwl6: { borderLeftWidth: 6 },
  p7: { padding: 28 },
  pt7: { paddingTop: 28 },
  pr7: { paddingRight: 28 },
  pb7: { paddingBottom: 28 },
  pl7: { paddingLeft: 28 },
  m7: { margin: 28 },
  mt7: { marginTop: 28 },
  mr7: { marginRight: 28 },
  mb7: { marginBottom: 28 },
  ml7: { marginLeft: 28 },
  br7: { borderRadius: 28 },
  bw7: { borderWidth: 7 },
  bwt7: { borderTopWidth: 7 },
  bwr7: { borderRightWidth: 7 },
  bwb7: { borderBottomWidth: 7 },
  bwl7: { borderLeftWidth: 7 },
  p8: { padding: 32 },
  pt8: { paddingTop: 32 },
  pr8: { paddingRight: 32 },
  pb8: { paddingBottom: 32 },
  pl8: { paddingLeft: 32 },
  m8: { margin: 32 },
  mt8: { marginTop: 32 },
  mr8: { marginRight: 32 },
  mb8: { marginBottom: 32 },
  ml8: { marginLeft: 32 },
  br8: { borderRadius: 32 },
  bw8: { borderWidth: 8 },
  bwt8: { borderTopWidth: 8 },
  bwr8: { borderRightWidth: 8 },
  bwb8: { borderBottomWidth: 8 },
  bwl8: { borderLeftWidth: 8 },
  p9: { padding: 36 },
  pt9: { paddingTop: 36 },
  pr9: { paddingRight: 36 },
  pb9: { paddingBottom: 36 },
  pl9: { paddingLeft: 36 },
  m9: { margin: 36 },
  mt9: { marginTop: 36 },
  mr9: { marginRight: 36 },
  mb9: { marginBottom: 36 },
  ml9: { marginLeft: 36 },
  br9: { borderRadius: 36 },
  bw9: { borderWidth: 9 },
  bwt9: { borderTopWidth: 9 },
  bwr9: { borderRightWidth: 9 },
  bwb9: { borderBottomWidth: 9 },
  bwl9: { borderLeftWidth: 9 },
  p10: { padding: 40 },
  pt10: { paddingTop: 40 },
  pr10: { paddingRight: 40 },
  pb10: { paddingBottom: 40 },
  pl10: { paddingLeft: 40 },
  m10: { margin: 40 },
  mt10: { marginTop: 40 },
  mr10: { marginRight: 40 },
  mb10: { marginBottom: 40 },
  ml10: { marginLeft: 40 },
  br10: { borderRadius: 40 },
  bw10: { borderWidth: 10 },
  bwt10: { borderTopWidth: 10 },
  bwr10: { borderRightWidth: 10 },
  bwb10: { borderBottomWidth: 10 },
  bwl10: { borderLeftWidth: 10 },
  px1: { paddingHorizontal: 4 },
  py1: { paddingVertical: 4 },
  mx1: { marginHorizontal: 4 },
  my1: { marginVertical: 4 },
  px2: { paddingHorizontal: 8 },
  py2: { paddingVertical: 8 },
  mx2: { marginHorizontal: 8 },
  my2: { marginVertical: 8 },
  px3: { paddingHorizontal: 12 },
  py3: { paddingVertical: 12 },
  mx3: { marginHorizontal: 12 },
  my3: { marginVertical: 12 },
  px4: { paddingHorizontal: 16 },
  py4: { paddingVertical: 16 },
  mx4: { marginHorizontal: 16 },
  my4: { marginVertical: 16 },
  px5: { paddingHorizontal: 20 },
  py5: { paddingVertical: 20 },
  mx5: { marginHorizontal: 20 },
  my5: { marginVertical: 20 },
  px6: { paddingHorizontal: 24 },
  py6: { paddingVertical: 24 },
  mx6: { marginHorizontal: 24 },
  my6: { marginVertical: 24 },
  px7: { paddingHorizontal: 28 },
  py7: { paddingVertical: 28 },
  mx7: { marginHorizontal: 28 },
  my7: { marginVertical: 28 },
  px8: { paddingHorizontal: 32 },
  py8: { paddingVertical: 32 },
  mx8: { marginHorizontal: 32 },
  my8: { marginVertical: 32 },
  px9: { paddingHorizontal: 36 },
  py9: { paddingVertical: 36 },
  mx9: { marginHorizontal: 36 },
  my9: { marginVertical: 36 },
  px10: { paddingHorizontal: 40 },
  py10: { paddingVertical: 40 },
  mx10: { marginHorizontal: 40 },
  my10: { marginVertical: 40 },
  g1: { gap: 4 },
  rg1: { rowGap: 4 },
  cg1: { columnGap: 4 },
  g2: { gap: 8 },
  rg2: { rowGap: 8 },
  cg2: { columnGap: 8 },
  g3: { gap: 12 },
  rg3: { rowGap: 12 },
  cg3: { columnGap: 12 },
  g4: { gap: 16 },
  rg4: { rowGap: 16 },
  cg4: { columnGap: 16 },
  g5: { gap: 20 },
  rg5: { rowGap: 20 },
  cg5: { columnGap: 20 },
  g6: { gap: 24 },
  rg6: { rowGap: 24 },
  cg6: { columnGap: 24 },
  g7: { gap: 28 },
  rg7: { rowGap: 28 },
  cg7: { columnGap: 28 },
  g8: { gap: 32 },
  rg8: { rowGap: 32 },
  cg8: { columnGap: 32 },
  g9: { gap: 36 },
  rg9: { rowGap: 36 },
  cg9: { columnGap: 36 },
  g10: { gap: 40 },
  rg10: { rowGap: 40 },
  cg10: { columnGap: 40 },
  fs8: { fontSize: 8 },
  fs10: { fontSize: 10 },
  fs12: { fontSize: 12 },
  fs14: { fontSize: 14 },
  fs16: { fontSize: 16 },
  fs18: { fontSize: 18 },
  fs20: { fontSize: 20 },
  fs22: { fontSize: 22 },
  fs24: { fontSize: 24 },
  fs26: { fontSize: 26 },
  fs28: { fontSize: 28 },
  fs30: { fontSize: 30 },
  fs32: { fontSize: 32 },
  btlr0: { borderTopLeftRadius: 0 },
  btrr0: { borderTopRightRadius: 0 },
  bblr0: { borderBottomLeftRadius: 0 },
  bbrr0: { borderBottomRightRadius: 0 },
  btlr1: { borderTopLeftRadius: 4 },
  btrr1: { borderTopRightRadius: 4 },
  bblr1: { borderBottomLeftRadius: 4 },
  bbrr1: { borderBottomRightRadius: 4 },
  btlr2: { borderTopLeftRadius: 8 },
  btrr2: { borderTopRightRadius: 8 },
  bblr2: { borderBottomLeftRadius: 8 },
  bbrr2: { borderBottomRightRadius: 8 },
  btlr3: { borderTopLeftRadius: 12 },
  btrr3: { borderTopRightRadius: 12 },
  bblr3: { borderBottomLeftRadius: 12 },
  bbrr3: { borderBottomRightRadius: 12 },
  btlr4: { borderTopLeftRadius: 16 },
  btrr4: { borderTopRightRadius: 16 },
  bblr4: { borderBottomLeftRadius: 16 },
  bbrr4: { borderBottomRightRadius: 16 },
  btlr5: { borderTopLeftRadius: 20 },
  btrr5: { borderTopRightRadius: 20 },
  bblr5: { borderBottomLeftRadius: 20 },
  bbrr5: { borderBottomRightRadius: 20 },
  btlr6: { borderTopLeftRadius: 24 },
  btrr6: { borderTopRightRadius: 24 },
  bblr6: { borderBottomLeftRadius: 24 },
  bbrr6: { borderBottomRightRadius: 24 },
  btlr7: { borderTopLeftRadius: 28 },
  btrr7: { borderTopRightRadius: 28 },
  bblr7: { borderBottomLeftRadius: 28 },
  bbrr7: { borderBottomRightRadius: 28 },
  btlr8: { borderTopLeftRadius: 32 },
  btrr8: { borderTopRightRadius: 32 },
  bblr8: { borderBottomLeftRadius: 32 },
  bbrr8: { borderBottomRightRadius: 32 },
  btlr9: { borderTopLeftRadius: 36 },
  btrr9: { borderTopRightRadius: 36 },
  bblr9: { borderBottomLeftRadius: 36 },
  bbrr9: { borderBottomRightRadius: 36 },
  btlr10: { borderTopLeftRadius: 40 },
  btrr10: { borderTopRightRadius: 40 },
  bblr10: { borderBottomLeftRadius: 40 },
  bbrr10: { borderBottomRightRadius: 40 },
  hrLine: {
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  borderDashed: {
    borderStyle: 'dashed',
  },
  borderDotted: {
    borderStyle: 'dotted',
  },
  borderSolid: {
    borderStyle: 'solid',
  },
  capitalize: {
    textTransform: 'capitalize',
  },
  lowercase: {
    textTransform: 'lowercase',
  },
  uppercase: {
    textTransform: 'uppercase',
  },
  mAuto: {
    margin: 'auto',
  },
  pAuto: {
    padding: 'auto',
  },
  mrAuto: {
    marginRight: 'auto',
  },
  prAuto: {
    paddingRight: 'auto',
  },
  mbAuto: {
    marginBottom: 'auto',
  },
  pbAuto: {
    paddingBottom: 'auto',
  },
  mlAuto: {
    marginLeft: 'auto',
  },
  plAuto: {
    paddingLeft: 'auto',
  },
  mtAuto: {
    marginTop: 'auto',
  },
  ptAuto: {
    paddingTop: 'auto',
  },
  textAlignAuto: {
    textAlign: 'auto',
  },
  textAlignCenter: {
    textAlign: 'center',
  },
  textAlignJustify: {
    textAlign: 'justify',
  },
  textAlignLeft: {
    textAlign: 'left',
  },
  textAlignRight: {
    textAlign: 'right',
  },
});
